fileVersion: 1
id: "5"
mappingDefinitions:
  SOURCE_TPCH:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  TARGET:
    database: JUSTIN_EDW
    schema: PRD_DEPLOY
name: PROD
type: Environment
