fileVersion: 1
id: "5"
mappingDefinitions:
  SOURCE_TASTYBYTES:
    database: FROSTBYTE_TASTY_BYTES
    schema: RAW_POS
  SOURCE_TASTYBYTES_CUSTOMER:
    database: FROSTBYTE_TASTY_BYTES
    schema: RAW_CUSTOMER
  TARGET:
    database: JUSTIN_EDW
    schema: PRD_DEPLOY
name: PROD
type: Environment
