fileVersion: 1
id: "5"
mappingDefinitions:
  SOURCE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  SRC_SEC_FILINGS:
    database: SEC_FILINGS
    schema: CYBERSYN
  SRC_TPCH:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  TARGET:
    database: JUSTIN_EDW
    schema: PRD_DEPLOY
  TGT_TPCH:
    database: JUSTIN_EDW
    schema: DEV_EDW
name: Production
type: Environment
