fileVersion: 1
id: "5"
mappingDefinitions:
  DWH:
    database: JUSTIN_EDW
    schema: PRD_EDW
  PUBLIC:
    database: JUSTIN_EDW
    schema: PUBLIC
  SRC_FIVETRAN_RETAIL:
    database: FIVETRAN_DATABASE
    schema: RETAIL_DATA
  SRC_SAMPLE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  SRC_WEATHER:
    database: GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI
    schema: STANDARD_TILE
  STAGE:
    database: JUSTIN_EDW
    schema: PRD_ETL
name: Production
type: Environment
