config:
  entities:
    nodeTypes:
      "173":
        defaultStorageLocation: null
        isDisabled: false
      "188":
        defaultStorageLocation: null
        isDisabled: false
      "194":
        defaultStorageLocation: null
        isDisabled: false
      "204":
        defaultStorageLocation: null
        isDisabled: false
      "205":
        defaultStorageLocation: null
        isDisabled: false
      "248":
        defaultStorageLocation: null
        isDisabled: false
  packageVariables: ""
fileVersion: 1
id: "@coalesce/base-node-types"
name: Base
packageID: "@coalesce/base-node-types"
releaseID: 0a545696-e27e-4a31-8124-681be0c1f7eb
type: Package
