config:
  entities:
    nodeTypes:
      "179":
        defaultStorageLocation: null
        isDisabled: false
      "388":
        defaultStorageLocation: null
        isDisabled: false
      "389":
        defaultStorageLocation: null
        isDisabled: false
      "390":
        defaultStorageLocation: null
        isDisabled: false
      "391":
        defaultStorageLocation: null
        isDisabled: true
  packageVariables: ""
fileVersion: 1
id: "@coalesce/base-node-types-advanced-deploy"
name: base
packageID: "@coalesce/base-node-types-advanced-deploy"
releaseID: 5ff1215e-84f0-4d46-944c-d2c211e6f52e
type: Package
