config:
  entities:
    nodeTypes:
      "179":
        defaultStorageLocation: null
        isDisabled: false
      "388":
        defaultStorageLocation: null
        isDisabled: false
      "389":
        defaultStorageLocation: null
        isDisabled: false
      "390":
        defaultStorageLocation: null
        isDisabled: false
      "391":
        defaultStorageLocation: null
        isDisabled: false
  packageVariables: ""
fileVersion: 1
id: "@coalesce/snowflake/base-node-types-advanced-deploy"
name: Base
packageID: "@coalesce/snowflake/base-node-types-advanced-deploy"
releaseID: 210b9cdb-6b98-42ba-bbd6-f07d845ee1e5
type: Package
